---
name: test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - name: "Install Poetry"
        uses: "snok/install-poetry@v1"
      - name: "Install dependencies"
        run: "poetry install --with tests"
      - name: "Lint"
        run: "poetry run make lint"
      - name: "Test"
        run: "poetry run make test"